---
- name: Set up Pelican Game Server Control Panel
  hosts: all
  become: yes

  vars:
    server_ip: "192.168.45.20"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - python3
          - python3-pip
          - python3-venv
          - nginx
          - supervisor
        state: present

    - name: Clone Pelican Game Server Control Panel repository
      git:
        repo: 'https://github.com/pelican-server/panel.git'
        dest: /opt/pelican-panel

    - name: Set up Python virtual environment
      command: python3 -m venv /opt/pelican-panel/venv
      args:
        creates: /opt/pelican-panel/venv

    - name: Install Python dependencies
      pip:
        requirements: /opt/pelican-panel/requirements.txt
        virtualenv: /opt/pelican-panel/venv

    - name: Create Nginx configuration file
      copy:
        content: |
          server {
              listen 80;
              server_name {{ server_ip }};

              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /static/ {
                  alias /opt/pelican-panel/static/;
              }
          }
        dest: /etc/nginx/sites-available/pelican
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/pelican
        dest: /etc/nginx/sites-enabled/pelican
        state: link
        force: yes

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
        force: yes

    - name: Create Supervisor configuration file
      copy:
        content: |
          [program:pelican_panel]
          command=/opt/pelican-panel/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 wsgi:app
          directory=/opt/pelican-panel
          user=www-data
          autostart=true
          autorestart=true
          stopasgroup=true
          killasgroup=true
          stderr_logfile=/var/log/supervisor/pelican_panel.err.log
          stdout_logfile=/var/log/supervisor/pelican_panel.out.log
        dest: /etc/supervisor/conf.d/pelican.conf
      notify:
        - Reload Supervisor

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reload Supervisor
      command: supervisorctl reload
