---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Installing Pi-Hole
      shell: sudo curl -sSL https://install.pi-hole.net | sudo bash /dev/stdin --unattended
